### ISSUE TITLE
Conversation tracking

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#2]
Currently, ChatterBot only responds to the last statement that was entered. For better conversations and more accurate responses it would be useful to track the last statements that were entered in a given conversation and use these details to determine what to say next.

Should the chatterbot's responses to the user be remembered as well? In the past these were stored in the database along with user inputs, however this caused issues with the chat bot learning the wrong output because it was recalling its own responses.
- [ ] Research how the weight of a statement in a conversation changes as the conversation goes on.
- [ ] Use statements from the current conversation to help determine the most appropriate response.
- [ ] Statements decrease in weight as time increases.
- Add set_persona method & set_user_persons() methods

It might be interesting to investigate the NLTK [PositiveNaiveBayesClassifier](http://www.nltk.org/api/nltk.classify.html) for determining if a statement shares a subject with a list of past statemets.

**Comment by gunthercox** [comment]
Commit 177ad7b314f56039f27f8b05f83a3f7b7d48448d introduces a parameter to pass the current conversation into the logic adapter. This makes it possible to access this information from within a future logic adapter that will make choices in based on the context of the current conversation.

**Comment by gunthercox** [comment]
Work is being done on the subtree branch (https://github.com/gunthercox/ChatterBot/tree/subtree) to support finding past conversations that are similar to the current one.

**Comment by rmdort** [comment]
This looks awesome.  Will past conversations be tied to the User?

**Comment by gunthercox** [comment]
Not yet, but in future additions that functionality will definitely be added.

**Comment by gunthercox** [comment]
Closing this ticket off as #276 is essentially the same thing, except with a more defined scope.
